### ISSUE TITLE
Benchmark crashes in Rust (wasm module)

### ISSUE THREAD

**Issue by christophwille** [christophwille/csharp-opa-wasm#4]
Added super-simple BenchmarkDotNet project at https://github.com/christophwille/csharp-opa-wasm/blob/master/spikes/BenchmarkOpaWasm/Program.cs

This crashes before taking measurements, details see attached log file. Seems some issue with the underlying wasm/runtime?:

```
thread '<unnamed>' panicked at 'allocate_for_function: "The paging file is too small for this operation to complete. (os error 1455)"', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
ExitCode != 0
```

[BenchmarkOpaWasm.WasmPolicyExecution-20200309-115410.log](https://github.com/christophwille/csharp-opa-wasm/files/4306206/BenchmarkOpaWasm.WasmPolicyExecution-20200309-115410.log)

**Comment by christophwille** [comment]
@peterhuene Do you know where this might be coming from? (so I can report it at the correct place). Thanks.

**Comment by peterhuene** [comment]
This is coming from Wasmtime. `allocate_for_function` is called when allocating trampolines per function and it was being done very inefficiently until recently.  Does the wasm module have a lot of functions perhaps?  Let me track down to see when (and if) the fixes around this made it in.

**Comment by christophwille** [comment]
The wasm is in this repo at https://github.com/christophwille/csharp-opa-wasm/tree/master/sample-policies

It is super-simple, I have attached the wasm2wat for it here.  [policy.wasm2wat.txt](https://github.com/christophwille/csharp-opa-wasm/files/4308120/policy.wasm2wat.txt)

**Comment by peterhuene** [comment]
So there were multiple fixes in this area, one of which made it in to 0.12.0 (https://github.com/bytecodealliance/wasmtime/pull/947) and one that is not yet in (https://github.com/bytecodealliance/wasmtime/pull/957).

The former reduced the number of trampolines generated from per-function to per-signature, which should greatly reduce the needed number of trampolines, allowing some trampolines to be shared between functions with the same signature.

The latter is to prevent 64K allocations *per trampoline* which is really inefficient.  We hope to have that fix in soon.

I'd still only expect this to be a problem with a module with a *lot* of distinct signatures or in a memory-constrained environment.

**Comment by peterhuene** [comment]
The module is super small with not many signatures, so I can't explain why you would be running into this issue.  I'll see if I can reproduce.

**Comment by peterhuene** [comment]
You may want to see if adding an `IDisposable` implementation to `OpaPolicy` to dispose of the instance and then disposing the policy in the benchmark method helps at all.  I suspect the benchmarking is iterating heavily on that method and thus creating a lot of instances without putting any pressure on the GC because it's all native allocations being done.

**Comment by christophwille** [comment]
I'll try that. I hadn't added IDisposable because OpaPolicy itself isn't holding the external resources (well, and I haven't decided on any sort of object model yet).

**Comment by christophwille** [comment]
I tested it with minimal changes as can be seen in https://github.com/christophwille/csharp-opa-wasm/commit/6fc45a2d708e095029e9959f17b654556e81bd5e. Yes, collecting the instances makes all the difference.

**Comment by christophwille** [comment]
Closing for Wasmtime 0.15
